# Generated by Django 4.0 on 2021-12-16 09:41

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profiles/default.jpeg', upload_to='profiles'),
        ),
    ]
